package ar.edu.utn.frc.tup.piv.llm.infrastructure.persistence;
import ar.edu.utn.frc.tup.piv.llm.domain.calibration.CalibrationRun;
import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository;
@Repository public class CalibrationRunRepository {private final JdbcTemplate j;public CalibrationRunRepository(JdbcTemplate j){this.j=j;}public CalibrationRun create(UUID c,UUID r,UUID g,UUID m,UUID k,UUID a){var old=findKey(c,k);if(old.isPresent())return old.get();UUID id=UUID.randomUUID();int n=j.update("insert into llm.calibration_runs(id,course_id,rubric_version_id,golden_set_version_id,model_deployment_id,reason,created_by_user_id,idempotency_key) select ?,?,?,?,?, 'MANUAL',?,? where exists(select 1 from llm.rubric_version_v2 x join llm.rubric_families f on f.id=x.family_id where x.id=? and x.state='PUBLISHED' and f.course_id=?) and exists(select 1 from llm.golden_set_versions x join llm.golden_set_families f on f.id=x.family_id where x.id=? and x.state='PUBLISHED' and f.course_id=?)",id,c,r,g,m,a,k,r,c,g,c);if(n==0)throw new IllegalStateException("Las versiones publicadas no pertenecen al curso");return new CalibrationRun(id,"QUEUED",0);}public Optional<UUID> claimNextQueued(){return j.query("select id from llm.calibration_runs where state='QUEUED' order by created_at for update skip locked limit 1",(r,n)->r.getObject(1,UUID.class)).stream().findFirst();}
public Optional<CalibrationRun> find(UUID c,UUID id){return q("select id,state::text,progress,rubric_version_id,golden_set_version_id,model_deployment_id,mae_final,max_individual_error,reason,created_at,finished_at from llm.calibration_runs where course_id=? and id=?",c,id);}
/** El worker solo tiene el runId tras claimNextQueued(), sin courseId. */
public Optional<CalibrationRun> findById(UUID id){return j.query("select id,state::text,progress,rubric_version_id,golden_set_version_id,model_deployment_id,mae_final,max_individual_error,reason,created_at,finished_at from llm.calibration_runs where id=?",(r,n)->new CalibrationRun(r.getObject(1,UUID.class),r.getString(2),r.getInt(3),r.getObject(4,UUID.class),r.getObject(5,UUID.class),r.getObject(6,UUID.class),r.getObject(7)!=null?r.getDouble(7):null,r.getObject(8)!=null?r.getInt(8):null,r.getString(9),r.getTimestamp(10)!=null?r.getTimestamp(10).toInstant():null,r.getTimestamp(11)!=null?r.getTimestamp(11).toInstant():null),id).stream().findFirst();}
public List<CalibrationRun> list(UUID c){return j.query("select id,state::text,progress,rubric_version_id,golden_set_version_id,model_deployment_id,mae_final,max_individual_error,reason,created_at,finished_at from llm.calibration_runs where course_id=? order by created_at desc",(r,n)->new CalibrationRun(r.getObject(1,UUID.class),r.getString(2),r.getInt(3),r.getObject(4,UUID.class),r.getObject(5,UUID.class),r.getObject(6,UUID.class),r.getObject(7)!=null?r.getDouble(7):null,r.getObject(8)!=null?r.getInt(8):null,r.getString(9),r.getTimestamp(10)!=null?r.getTimestamp(10).toInstant():null,r.getTimestamp(11)!=null?r.getTimestamp(11).toInstant():null),c);}
public void recordProgress(UUID id,int progress,Double maeFinal,Integer maxIndividualError){j.update("update llm.calibration_runs set progress=?,mae_final=?,max_individual_error=? where id=?",progress,maeFinal,maxIndividualError,id);}
private Optional<CalibrationRun> findKey(UUID c,UUID k){return q("select id,state::text,progress,rubric_version_id,golden_set_version_id,model_deployment_id,mae_final,max_individual_error,reason,created_at,finished_at from llm.calibration_runs where course_id=? and idempotency_key=?",c,k);}
private Optional<CalibrationRun> q(String s,UUID a,UUID b){return j.query(s,(r,n)->new CalibrationRun(r.getObject(1,UUID.class),r.getString(2),r.getInt(3),r.getObject(4,UUID.class),r.getObject(5,UUID.class),r.getObject(6,UUID.class),r.getObject(7)!=null?r.getDouble(7):null,r.getObject(8)!=null?r.getInt(8):null,r.getString(9),r.getTimestamp(10)!=null?r.getTimestamp(10).toInstant():null,r.getTimestamp(11)!=null?r.getTimestamp(11).toInstant():null),a,b).stream().findFirst();}
}
